//var x: int = 5

func main(): func
{
	if (main(5)) return 1;
	//return test(5)
}
/*
	if (1) {
		var i: int = 0
	}
	var test: func = func test(): int {
		if (1) {
			var i: int = x
		}
	}
	if (1) {
		var i: int = 0
	}
	while (false) {
		if (1) {
			if (1) {
				var i: int = 0
			}
		}
		var y: int = (main() + 55) / 60^5
		return y
	}
	//return func(): dynamic { return 0; }
