var yay: int = 2;
var d: int = nil;
var fetch: func = nil;
var length: func = nil;

func idk_lolll(): int
{
    var x: int = fetch;
    var y: int = 1/4;;;;;
    return 9 + 10;
    var a: int = fetch;
    var i: int = 5;
    var b: int = i + (d / yay)^yay;

    func testing_my_language(): int
    {
        var a: int = 5;
        return a;
    }

    if length*(d) == testing_my_language {
        var gk: int = 999;;;;;
    }
    while y* 6 > 15 {
        var s: int = 0;
    }
    return 0;
}
