var yay: int = 2;
var d: string = "-"*10 + "\x1b[0;31mnil\x1b[0m" + "-"*10;
var fetch: int = nil;
var length: int = nil;

/*
func idk_lolll(): int
{
    var x: int = fetch;
    var y: int = 1/4;;;;;
    return 9 + 10;
    var a: int = fetch;
    var i: int = 5;
    var b: int = i + (d / yay)^yay;

    {{{{{{{{{{{{var ddd:int=i}var ddd:int=i}}}}}}}}}}}

    func testing_my_language(): int
    {
        var a: int = 5;
        return a;
    }

    if length*(d) == testing_my_language {
        var gk: int = 999;;;;;
    }
    while y* 6 > 15 {
        var s: int = 0;
    }
    return 0;
}
